name: CMake Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Cache APT packages
      uses: actions/cache@v4
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-${{ hashFiles('.github/workflows/**') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Install dependencies 
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang \
          cmake \
          libboost-all-dev \
          libssl-dev \
          ninja-build \
          nlohmann-json3-dev \
          libcurl4-openssl-dev

    - name: Configure CMake
      run: |
        cmake -B build -G Ninja \
          -DCMAKE_C_COMPILER=clang \
          -DCMAKE_CXX_COMPILER=clang++
      
    - name: Build
      run: cmake --build build -j$(nproc)